name: Build Docs (Dokka) + AI Summary

on:
  push:
    branches: [ "main" ]

permissions: { contents: write }

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "21" }
      - uses: gradle/actions/setup-gradle@v3

      - name: Build Dokka
        run: ./gradlew dokkaHtml

      - name: Collect recent changes
        run: |
          set -euo pipefail
          git fetch --tags --depth=1 || true
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then RANGE="$LAST_TAG..HEAD"; else RANGE=""; fi
          echo "### Changes since $LAST_TAG" > DOCS_CONTEXT.md
          if [ -n "$RANGE" ]; then
            git --no-pager log $RANGE --pretty=format:'- %s' >> DOCS_CONTEXT.md
          else
            git --no-pager log --pretty=format:'- %s' -n 50 >> DOCS_CONTEXT.md
          fi
          head -n 300 DOCS_CONTEXT.md > DOCS_CTX_TRIMMED.md

      - name: AI Key Features (short)
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${OPEN_ROUTER_API_KEY:-}" ]; then
            echo "_AI summary unavailable_" > docs/KEY_FEATURES.md
          else
            SYS='Сформируй короткий раздел "**Key Features**" (5-7 bullets) по последним изменениям. Только маркдаун-список.'
            USR=$(cat DOCS_CTX_TRIMMED.md)
            JSON=$(jq -n --arg s "$SYS" --arg u "$USR" \
              '{model:"openai/gpt-4o-mini",messages:[{"role":"system","content":$s},{"role":"user","content":$u}],temperature:0.2}')
            RESP=$(curl -sS https://openrouter.ai/api/v1/chat/completions \
              -H "Authorization: Bearer ${OPEN_ROUTER_API_KEY}" -H "Content-Type: application/json" -d "$JSON")
            OUT=$(echo "$RESP" | jq -r '.choices[0].message.content // empty')
            mkdir -p docs
            printf "%s\n" "${OUT:-_AI summary unavailable_}" > docs/KEY_FEATURES.md
          fi
          # приложим к gh-pages
          mkdir -p public
          cp -R build/dokka/html/* public/
          cp docs/KEY_FEATURES.md public/KEY_FEATURES.md

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public