name: OpenRouter Secret Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check OPEN_ROUTER_API_KEY presence
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${OPEN_ROUTER_API_KEY:-}" ]; then
            echo "⛔ Secret OPEN_ROUTER_API_KEY is NOT available to this workflow."
            exit 1
          fi
          echo "✅ Secret OPEN_ROUTER_API_KEY is present."

      - name: Call OpenRouter /models
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          RESP=$(curl -sS https://openrouter.ai/api/v1/models \
            -H "Authorization: Bearer ${OPEN_ROUTER_API_KEY}" \
            -H "HTTP-Referer: https://github.com/${{ github.repository }}" \
            -H "X-Title: OpenRouter Smoke")
          # В случае ошибки OpenRouter вернёт { "error": {...} }
          if echo "$RESP" | jq -e '.error' >/dev/null 2>&1; then
            echo "OpenRouter returned error:"; echo "$RESP" | jq .error; exit 1
          fi
          echo "✅ OpenRouter responded ok."