name: OpenRouter Secret Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check OPEN_ROUTER_API_KEY presence
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${OPEN_ROUTER_API_KEY:-}" ]; then
            echo "⛔ Secret OPEN_ROUTER_API_KEY is NOT available to this workflow."
            exit 1
          fi
          echo "✅ Secret OPEN_ROUTER_API_KEY is present."

      - name: Sanitize and call OpenRouter /models
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          sanitize_one_line() {
            printf '%s' "${1-}" | tr -d '\r\n' | sed -E 's/^[[:space:]"]+//; s/[[:space:]"]+$//'
          }
          API_KEY="$(sanitize_one_line "${OPEN_ROUTER_API_KEY-}")"
          echo "API key length after sanitize: $(printf '%s' "$API_KEY" | wc -c)"
          RESP=$(curl -sS https://openrouter.ai/api/v1/models \
            -H "Authorization: Bearer ${API_KEY}" \
            -H "HTTP-Referer: https://github.com/${{ github.repository }}" \
            -H "X-Title: OpenRouter Smoke")
          if echo "$RESP" | jq -e '.error' >/dev/null 2>&1; then
            echo "OpenRouter returned error:"; echo "$RESP" | jq .error; exit 1
          fi
          echo "✅ OpenRouter responded ok."