name: OpenRouter Secret Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check OPEN_ROUTER_API_KEY presence
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${OPEN_ROUTER_API_KEY:-}" ]; then
            echo "⛔ Secret OPEN_ROUTER_API_KEY is NOT available to this workflow."
            exit 1
          fi
          echo "✅ Secret OPEN_ROUTER_API_KEY is present."

      - name: Sanitize and call OpenRouter /models
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          cleaned="$(printf '%s' "${OPEN_ROUTER_API_KEY-}" \
            | tr -d '\r\n' \
            | sed -E 's/^[[:space:]"]+//; s/[[:space:]"]+$//' \
            | perl -CSDA -pe 's/\x{200B}|\x{200C}|\x{200D}|\x{FEFF}//g; s/\p{Space}//g')"
          echo "API key length after sanitize: $(printf '%s' "$cleaned" | wc -c)"
          RESP=$(curl -sS https://openrouter.ai/api/v1/models \
            -H "Authorization: Bearer ${cleaned}" \
            -H "HTTP-Referer: https://github.com/${{ github.repository }}" \
            -H "X-Title: OpenRouter Smoke")
          if echo "$RESP" | jq -e '.error' >/dev/null 2>&1; then
            echo "OpenRouter returned error:"; echo "$RESP" | jq .error; exit 1
          fi
          echo "✅ OpenRouter responded ok."