name: OpenRouter Auth Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check OPEN_ROUTER_API_KEY presence
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${OPEN_ROUTER_API_KEY:-}" ]; then
            echo "⛔ Secret OPEN_ROUTER_API_KEY is NOT available to this workflow."
            exit 1
          fi
          echo "✅ Secret OPEN_ROUTER_API_KEY is present."

      - name: Sanitize key and ping /v1/chat/completions (auth required)
        env:
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
          LLM_MODEL: ${{ vars.LLM_MODEL }}
          REPO_URL: ${{ format('{0}/{1}', github.server_url, github.repository) }}
        run: |
          set -euo pipefail

          # Санитизация ключа (без YAML-каверз и без печати самого значения)
          cleaned="$(printf '%s' "${OPEN_ROUTER_API_KEY-}" \
            | tr -d '\r\n' \
            | sed -E 's/^[[:space:]"]+//; s/[[:space:]"]+$//' \
            | perl -CSDA -pe 's/\x{200B}|\x{200C}|\x{200D}|\x{FEFF}//g')"

          LEN="$(printf '%s' "$cleaned" | wc -c)"
          FP="$(printf '%s' "$cleaned" | sha256sum | cut -c1-8)"
          echo "API key length after sanitize: $LEN"
          echo "API key fingerprint: $FP"

          MODEL="${LLM_MODEL:-deepseek/deepseek-r1:free}"
          REQ=$(jq -n --arg m "$MODEL" \
                 '{model:$m, messages:[{"role":"user","content":"ping"}], max_tokens:16, temperature:0.0}')

          RESP=$(curl -sS -w "\n%{http_code}" https://openrouter.ai/api/v1/chat/completions \
            -H "Authorization: Bearer ${cleaned}" \
            -H "Content-Type: application/json" \
            -H "HTTP-Referer: ${REPO_URL}" \
            -H "X-Title: OpenRouter Smoke" \
            -d "$REQ")

          BODY=$(printf '%s' "$RESP" | head -n -1)
          CODE=$(printf '%s' "$RESP" | tail -n 1)

          echo "HTTP: $CODE"
          echo "Raw body:"
          echo "$BODY" | jq . || echo "$BODY"

          if [ "$CODE" -eq 401 ]; then
            echo "❌ Unauthorized (401). Проверь OPEN_ROUTER_API_KEY (пустой/битый) или ограничение по доменам."
            exit 1
          fi

          if [ "$CODE" -eq 403 ]; then
            echo "❌ Forbidden (403). На ключе включены ограничения 'Allowed sites'. Добавь '${REPO_URL}' или 'https://github.com' в список разрешённых доменов на OpenRouter."
            exit 1
          fi

          if echo "$BODY" | jq -e '.error' >/dev/null 2>&1; then
            echo "❌ OpenRouter returned error."
            exit 1
          fi

          OUT=$(echo "$BODY" | jq -r '.choices[0].message.content // empty')
          if [ -z "$OUT" ]; then
            echo "❌ No content in response."
            exit 1
          fi

          echo "✅ Auth OK. Model: $MODEL; Reply: $(echo "$OUT" | head -c 60)"